server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    mongodb:
      uri: ${MONGO_URI}

logging:
  level:
    root: INFO
    com.neoutilix: INFO

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000
